package com.example.MedQueue.doctor.enums;

public enum Specialist {
    GENERAL_PRACTITIONER,
    PEDIATRICIAN,
    CARDIOLOGIST,
    NEUROLOGIST,
    DERMATOLOGIST,
    GYNECOLOGIST,
    ORTHOPEDIC_SURGEON,
    PSYCHIATRIST,
    RADIOLOGIST,
    ENDOCRINOLOGIST,
    ONCOLOGIST,
    UROLOGIST,
    GASTROENTEROLOGIST,
    OTOLARYNGOLOGIST,
    OPHTHALMOLOGIST,
    DENTIST,
    NEPHROLOGIST,
    HEMATOLOGIST,
    PULMONOLOGIST,
    RHEUMATOLOGIST,
    SURGEON,
    ANESTHESIOLOGIST,
    PATHOLOGIST,
    IMMUNOLOGIST,
    INFECTIOUS_DISEASE_SPECIALIST

}
